### ISSUE TITLE
No defined directory

### ISSUE THREAD

**Issue by STCNO** [nhalstead/nhalstead.github.io#3]
Add Simple-Discord-Bot/ directory and its files to get us to the invite!

**Comment by nhalstead** [comment]
All of the Website Content Related to the Project is stored in the `/docs` Directory in the Repository.
You can find it [here](https://github.com/nhalstead/Simple-Discord-Bot/tree/master/docs).

The website address is `https://nhalstead.github.io/Simple-Discord-Bot/`
